version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
