version: 2
updates:
  - package-ecosystem: "npm"
    has: "patch"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    has: "patch"
    directory: "/"
    schedule:
      interval: "weekly"
