version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Amsterdam"
    ignore:
      - dependency-name: "chalk"
    reviewers:
      - "DragonicDefson"
    labels:
      - "npm"
      - "dependencies"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Amsterdam"
    reviewers:
      - "DragonicDefson"
    labels:
      - "docker"
      - "dependencies"
