version: '3.9'
services:
  gq-discord-bot:
    image: dragonicdefson/gq-discord-bot:latest
    container_name: gq-discord-bot
    network_mode: host
    ports:
      - "0.0.0.0:8484:8484/tcp"
    volumes:
      - /var/log/gq-discord-bot/:/usr/src/app/docker-compose/
      - /var/www/vhosts/merciantnetwork.com/httpdocs/api/config/global/:/usr/src/app/config/global/
    restart: unless-stopped
